# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    increment_build_number

    # add actions here: https://docs.fastlane.tools/actions
    build_ios_app(
      output_directory: "build",
      output_name: "app.ipa", 
      export_method: "development"
    )
  end

  lane :ac_upload do
    appcenter_upload(
      owner_name: ENV["AC_OWNER"],
      app_name: ENV["AC_APP"],
      ipa: "./build/app.ipa",
      dsym: "./build/app.app.dSYM.zip",
      group: "Collaborators,Test",
      mandatory_update: true,
      notify_testers: false
    )
  end

  lane :sxs_upload do
    appcenter_upload(
      owner_name: ENV["HA_OWNER"],
      app_name: ENV["HA_APP"],
      ipa: "./build/app.ipa",
      group: "Collaborators,All-users-of-ios-native-fastlane-demo",
      mandatory_update: true,
      notify_testers: true
    )
  end
end
