# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    build_ios_app(
      output_directory: "build",
      output_name: "app.ipa", 
      export_method: "development"
    )
  end

  lane :upload do
    appcenter_upload(
      owner_name: "evkhramk",
      app_name: "ios-native-appcenter-demo",
      ipa: "./build/app.ipa",
      group: "Collaborators",
      mandatory_update: true
    )
  end
end
